#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rutorrent"
name = "ruTorrent"
description.en = "Web front-end for rTorrent"
description.fr = "Interface web frontale pour rTorrent"

version = "5.3.5~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "free"
admindoc = "https://doc.yunohost.org/dev/packaging/"
code = "https://github.com/Novik/ruTorrent"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Novik/ruTorrent/archive/refs/tags/v5.3.5.tar.gz"
    sha256 = "756175c329a663c4ddf951cd77a2ead7db6edf260f9227da2b3522d362c3e1c7"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "php8.5-simplexml, php8.5-curl, php8.5-mbstring, php8.5-zlib "
